Merge remaining upstream/stable/15 changes

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -35,6 +35,13 @@ f_include $BSDCFG_SHARE/dialog.subr
 ############################################################ GLOBALS
 
 #
+# List of environment variables that may be defined by the user, but modified
+# during the installation process. They are then restored when restarting this
+# script.
+#
+user_env_vars="BSDINSTALL_DISTSITE DISTRIBUTIONS WORKAROUND_GPTACTIVE WORKAROUND_LENOVO ZFSBOOT_PARTITION_SCHEME"
+
+#
 # Strings that should be moved to an i18n file and loaded with f_include_lang()
 #
 hline_arrows_tab_enter="Press arrows, TAB or ENTER"
@@ -90,6 +97,7 @@ error()
 		--yes-label "$msg_restart" \
 		--yesno "$prompt" $height $width
 	then
+		environment_restore
 		exec $0
 		# NOTREACHED
 	fi
@@ -138,12 +146,45 @@ dialog_workaround()
 		--yesno "$prompt" $height $width
 }
 
+# environment_restore
+#
+# Restore a list of environment variables when this script is restarted.
+#
+environment_restore()
+{
+	for var in $user_env_vars; do
+		eval "if [ -n \"\${ORIG_$var}\" -o -z \"\${ORIG_$var-z}\" ]; then $var=\${ORIG_$var}; else unset $var; fi"
+	done
+}
+
+# environment_save
+#
+# Save any user-defined environment variable that may be modified during the
+# installation process. They are then restored when restarting this script.
+#
+environment_save()
+{
+	for var in $user_env_vars; do
+		eval "if [ -n \"\${$var}\" -o -z \"\${$var-z}\" ]; then ORIG_$var=\${$var}; else unset ORIG_$var; fi"
+	done
+}
+
 ############################################################ MAIN
 
 f_dprintf "Began Installation at %s" "$( date )"
 
+environment_save
+
 rm -rf $BSDINSTALL_TMPETC
 mkdir $BSDINSTALL_TMPETC
+
+# With pkgbase, pkg OOM has been observed with QEMU-default 128 MiB memory size.
+# Ensure we have at least about 256 MiB (with an allowance for rounding etc.).
+physmem=$(($(sysctl -n hw.physmem) / 1048576))
+if [ $physmem -lt 200 ]; then
+        bsddialog --backtitle "$OSNAME Installer" --title "Warning" \
+	    --msgbox "Insufficient physical memory (${physmem} MiB) detected. At least 256 MiB is recommended. The installer or installed system may not function correctly." 0 0
+fi
 
 [ -f /usr/libexec/bsdinstall/local.pre-everything ] && f_dprintf "Running local.pre-everything" && sh /usr/libexec/bsdinstall/local.pre-everything "$BSDINSTALL_CHROOT"
 
@@ -153,36 +194,75 @@ trap true SIGINT	# This section is optional
 trap error SIGINT	# Catch cntrl-C here
 if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then bsdinstall hostname || error "Set hostname failed"; fi
 
-export DISTRIBUTIONS="${DISTRIBUTIONS:-base.txz kernel.txz}"
-if [ -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
-	DISTMENU=`awk -F'\t' '!/^(kernel\.txz|base\.txz)/{print $1,$5,$6}' $BSDINSTALL_DISTDIR/MANIFEST`
-	DISTMENU="$(echo ${DISTMENU} | sed -E 's/\.txz//g')"
+if [ -f /usr/freebsd-packages/repos/FreeBSD-base-offline.conf ]; then
+	HAVE_BASE_PACKAGES=yes
+	PKGBASE_DEFAULT_BUTTON=--default-no
+else
+	unset HAVE_BASE_PACKAGES
+	unset PKGBASE_DEFAULT_BUTTON
+fi
 
-	if [ -n "$DISTMENU" ]; then
-		exec 5>&1
-		EXTRA_DISTS=$( eval bsddialog \
-		    --backtitle \"$OSNAME Installer\" \
-		    --title \"Distribution Select\" --nocancel --separate-output \
-		    --checklist \"Choose optional system components to install:\" \
-		    0 0 0 $DISTMENU \
-		2>&1 1>&5 )
-		for dist in $EXTRA_DISTS; do
-			export DISTRIBUTIONS="$DISTRIBUTIONS $dist.txz"
-		done
+if [ ! -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
+	PKGBASE=yes
+else
+	bsddialog --backtitle "$OSNAME Installer" --title "Select Installation Type" \
+		--yes-label "Traditional" --no-label "Packages (Experimental)" --yesno \
+		$PKGBASE_DEFAULT_BUTTON \
+		"Would you like to install the base system using traditional distribution sets or packages (experimental)?" 0 0
+	if [ $? -eq 1 ]; then
+		PKGBASE=yes
 	fi
 fi
 
-FETCH_DISTRIBUTIONS=""
-for dist in $DISTRIBUTIONS; do
-	if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
-		FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
+if [ "$PKGBASE" == yes ]; then
+	if [ "$HAVE_BASE_PACKAGES" == yes ]; then
+		bsddialog --backtitle "$OSNAME Installer" --title "Network or Offline Installation" \
+		    --yes-label "Network" --no-label "Offline (Limited Packages)" --yesno \
+		    "Would you like to fetch packages from the internet or use the limited set of packages included in this installation media?" 0 0
+		if [ $? -eq 1 ]; then
+			export BSDINSTALL_PKG_REPOS_DIR=/usr/freebsd-packages/repos/
+		else
+			bsdinstall netconfig || error
+			NETCONFIG_DONE=yes
+		fi
+	else
+		bsddialog --backtitle "$OSNAME Installer" --title "Network Installation" \
+		    --msgbox "No base system packages are included in this installation media. The next few screens will allow you to configure networking." 0 0
+		bsdinstall netconfig || error
+		NETCONFIG_DONE=yes
 	fi
-done
+else
+	export DISTRIBUTIONS="${DISTRIBUTIONS:-base.txz kernel.txz}"
+	if [ -f $BSDINSTALL_DISTDIR/MANIFEST ]; then
+		DISTMENU=`awk -F'\t' '!/^(kernel\.txz|base\.txz)/{print $1,$5,$6}' $BSDINSTALL_DISTDIR/MANIFEST`
+		DISTMENU="$(echo ${DISTMENU} | sed -E 's/\.txz//g')"
 
-if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
-	bsddialog --backtitle "$OSNAME Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
-	bsdinstall netconfig || error
-	NETCONFIG_DONE=yes
+		if [ -n "$DISTMENU" ]; then
+			exec 5>&1
+			EXTRA_DISTS=$( eval bsddialog \
+			    --backtitle \"$OSNAME Installer\" \
+			    --title \"Distribution Select\" --nocancel --separate-output \
+			    --checklist \"Choose optional system components to install:\" \
+			    0 0 0 $DISTMENU \
+			2>&1 1>&5 )
+			for dist in $EXTRA_DISTS; do
+				export DISTRIBUTIONS="$DISTRIBUTIONS $dist.txz"
+			done
+		fi
+	fi
+
+	FETCH_DISTRIBUTIONS=""
+	for dist in $DISTRIBUTIONS; do
+		if [ ! -f $BSDINSTALL_DISTDIR/$dist ]; then
+			FETCH_DISTRIBUTIONS="$FETCH_DISTRIBUTIONS $dist"
+		fi
+	done
+
+	if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
+		bsddialog --backtitle "$OSNAME Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
+		bsdinstall netconfig || error
+		NETCONFIG_DONE=yes
+	fi
 fi
 
 rm -f $PATH_FSTAB
@@ -339,16 +419,20 @@ esac
 
 [ -f /usr/libexec/bsdinstall/local.pre-fetch ] && f_dprintf "Running local.pre-fetch" && sh /usr/libexec/bsdinstall/local.pre-fetch "$BSDINSTALL_CHROOT"
 
-if [ -n "$FETCH_DISTRIBUTIONS" ]; then
-	exec 5>&1
-	export BSDINSTALL_DISTDIR=$(`dirname $0`/fetchmissingdists 2>&1 1>&5)
-	FETCH_RESULT=$?
-	exec 5>&-
+if [ "$PKGBASE" == yes ]; then
+	bsdinstall pkgbase || error "Installation of base system packages failed"
+else
+	if [ -n "$FETCH_DISTRIBUTIONS" ]; then
+		exec 5>&1
+		export BSDINSTALL_DISTDIR=$(`dirname $0`/fetchmissingdists 2>&1 1>&5)
+		FETCH_RESULT=$?
+		exec 5>&-
 
-	[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"
+		[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"
+	fi
+	bsdinstall checksum || error "Distribution checksum failed"
+	bsdinstall distextract || error "Distribution extract failed"
 fi
-bsdinstall checksum || error "Distribution checksum failed"
-bsdinstall distextract || error "Distribution extract failed"
 
 # Set up boot loader
 bsdinstall bootconfig || error "Failed to configure bootloader"
@@ -391,7 +475,7 @@ if [ -z "$BSDINSTALL_SKIP_MANUAL" ]; then
 		clear
 		echo This shell is operating in a chroot in the new system. \
 		    When finished making configuration changes, type \"exit\".
-		chroot "$BSDINSTALL_CHROOT" /bin/sh 2>&1
+		chroot "$BSDINSTALL_CHROOT" /bin/sh -l 2>&1
 	fi
 fi
 
