Sync with upstream
This specifically fixes #38, and also updates the logic on Intel devices

commit f5931e3cf10aa2bef72a940e05845dd62d5a84e8
Author: Marcel <mk@freeshell.de>
Date:   Fri Mar 5 17:10:23 2021 +0100

    Add support for VMware.

commit 1fa9fe562bd9ca20765ef8d048d089d31d6d0fc1
Author: Marcel <mk@freeshell.de>
Date:   Fri Mar 5 17:09:57 2021 +0100

    Remove redundant line.

commit c4a44d086cb61b6a71958ca071eae56c56a778eb
Author: Marcel <mk@freeshell.de>
Date:   Sat Feb 20 10:35:03 2021 +0100

    Mounting / with -o sync doesn't seem to significantly reduce filesystem damage after a crash.

commit 7f681067f445526c9a0e69be4d5dca3b3967a876
Author: Marcel Kaiser <mk@freeshell.de>
Date:   Tue Feb 16 22:46:09 2021 +0100

    Change probe order. Since most Intel CPUs today have an IGPU, it is likely that initgfx will detect and use the IGPU before probing for an ATI/AMD graphics card.

commit c663c0073ed0b33c48863eef85f3c540566cc2a1
Author: Marcel <mk@freeshell.de>
Date:   Mon Feb 8 18:57:03 2021 +0100

    Temporarily mount / with -o sync which can reduce filesystem damage on crash.

commit 78a6567d72ba267f3eb58be5eb03135124ea77c8
Author: Marcel <mk@freeshell.de>
Date:   Sun Feb 7 20:53:02 2021 +0100

    Add an option to the boot menu to disable automatic graphics detection.

commit 750f46215cb97d25247414e04a814a757eb6a825
Author: Marcel <mk@freeshell.de>
Date:   Sun Jan 3 20:27:39 2021 +0100

    Change get_device_info() to also work under FreeBSD>=13, where pciconf outputs vendor and device separately

commit 1277288a1b779549e755d0b75a08e873c97a7049
Author: Marcel <mk@freeshell.de>
Date:   Mon Dec 28 22:14:05 2020 +0100

    Instead of writing to rc.conf directly, use a temporary file. Copy the temporary file back to /etc/rc.conf when done. This should prevent file corruption in case of a crash (Hi, Nvidia!)

commit e5bb8c1abf0433bd41d7dc4f8a6455a64084dfcf
Author: Marcel <mk@freeshell.de>
Date:   Sat Dec 26 23:19:28 2020 +0100

    Decrease delay

commit 7a3d2791ca1d3a169373e761d8f5ff1d69f65e05
Author: Marcel <mk@freeshell.de>
Date:   Sat Dec 26 21:26:10 2020 +0100

    - When testing X use xmessage to show a message for 10s. If xmessage is not available, sleep for 10s.
    - Copy the Nvidia files to /nvidia/.../modules/{drivers,extensions}
    - Omit copying vdpau directory. It it under the dynamic link path and will be found.
    - Make sure the symlinks to /nvidia/... under /usr/local/.../modules/{drivers,extensions} are still present. Recreate them if they were overwritten.
    - Waiting after loading the Nvidia module doesn't seem to have an impact on the crashing problem with the 340 driver. Remove it.
    - Change delay after testing X back to 3s.

commit 986fc3d63d239ec17befac495ce6c18b71183941
Author: Marcel <mk@freeshell.de>
Date:   Sat Dec 26 10:40:05 2020 +0100

    - Add a __wait() function.
    - Wait 10s after loading the nvidia module, and wait 10s after the Xorg test to prevent spontaneous reboots caused by the nvidia (340) module.

commit d5c836d60c72793bfef24c95af83926e294cc630
Author: Marcel <mk@freeshell.de>
Date:   Mon Dec 14 17:27:51 2020 +0100

    Remove drm-legacy-kmod, which is obsolete, and expires on 2020-12-31.

diff --git a/overlays/uzip/initgfx/files/etc/rc.d/initgfx b/overlays/uzip/initgfx/files/etc/rc.d/initgfx
--- a/overlays/uzip/initgfx/files/etc/rc.d/initgfx
+++ b/overlays/uzip/initgfx/files/etc/rc.d/initgfx
@@ -50,6 +50,7 @@ path_initgfx_xorg_templates="/etc/${name}_xorg.cfg"
 path_initgfx_device_db="/etc/${name}_device.db"
 
 path_cfg_test_dir="/tmp/${name}.$$"
+path_tmp_rc_conf="/tmp/rc.conf.$$"
 
 # Include device info DB
 . ${path_initgfx_device_db}
@@ -113,24 +114,54 @@ set_kldconfig_path()
 
 test_x()
 {
+	local cmd
+
 	if [ ! -d "${path_cfg_test_dir}" ]; then
 		mkdir "${path_cfg_test_dir}" 2>/dev/null
 	fi
 	cp "${path_xorg_cfg}" "${path_cfg_test_dir}"
+	if [ -x /usr/local/bin/xmessage ]; then
+		cmd="/usr/local/bin/xmessage -buttons '' -timeout 3"
+		cmd="${cmd} -center 'Please wait ...'"
+	else
+		cmd="sleep 3"
+	fi
 	PATH="${PATH}:/usr/local/bin" /usr/local/bin/xinit \
-		/usr/bin/true -- -configdir "${path_cfg_test_dir}"
+		/bin/sh -c "${cmd}; /usr/bin/true" -- -configdir \
+			"${path_cfg_test_dir}"
 }
 
-get_device_info() {
-	local chip
+get_device_info()
+{
 	unit=$(sysctl -n hw.pci.default_vgapci_unit)
 	[ -z "$unit" -o "$unit" =  "-1" ] && unit=0
-	chip=$(pciconf -lv | grep ^vgapci${unit} | head -1 | \
-		sed -E 's#.* chip=0x([0-9a-z]{4})([0-9a-z]{4}).*$#\1:\2#')
-	busID=$(pciconf -lv | grep ^vgapci${unit} | head -1 | \
-		sed -E 's/^vgapci[0-9]@pci[0-9]:([0-9:]+):.*$/\1/')
-	vendor=$(echo "${chip}" | cut -d: -f2)
-	device=$(echo "${chip}" | cut -d: -f1)
+	local info=$(pciconf -lv | grep "^vgapci${unit}" | awk -F'[ \t]+' ' {
+		for (i = 1; i <= NF; i++) {
+			if ($i ~ /^vgapci[0-9]/) {
+				if (split($i, a, ":") < 4)
+					exit(1);
+				busID = sprintf("%d:%d:%d", a[2], a[3], a[4])
+			} else if ($i ~ /^chip=/) {
+				device = substr($i, 8, 4);
+				vendor = substr($i, 12, 4);
+			} else if ($i ~ /^vendor=/) {
+				split($i, a, /=0x/);
+				vendor = a[2];
+			} else if ($i ~ /^device=/) {
+				split($i, a, /=0x/);
+				device = a[2];
+			}
+		}
+	}
+	END {
+		printf("%s %s %s", busID, vendor, device);
+	}')
+	set -- $info
+	device=$3; vendor=$2; busID=$1
+	if [ -z "${vendor}" -o -z "${device}" -o -z "${busID}" ]; then
+		echo "${name}: Error parsing 'pciconf' output"
+		exit 1
+	fi
 }
 
 rc_conf_d_ldconfig()
@@ -141,22 +172,31 @@ ldconfig_paths="\${ldconfig_paths} $1"
 rc_conf_d_END
 }
 
+__wait()
+{
+	n=$1
+	while [ $n -gt 0 ]; do
+		printf "\rWaiting %02d seconds" $n
+		n=$((n - 1))
+		sleep 1
+	done
+	echo
+}
+
 setup_intel()
 {
 	local kmod
 
 	[ "${vendor}" != 8086 ] && return 1
 	if i915_drm_legacy_ids | grep -iq ${device}; then
-		kmod="${path_drm_legacy}/i915kms.ko"
 		xorg_cfg_intel > "${path_xorg_cfg}"
 	else
-		kmod="/boot/modules/i915kms.ko"
 		xorg_cfg_modesetting > "${path_xorg_cfg}"
 	fi
+	kmod="/boot/modules/i915kms.ko"
 	set_kldconfig_path "${kmod}"
 	kldload "${kmod}"
-	set_kldconfig_path "${kmod}"
-	sysrc initgfx_kmods="${kmod}"
+	sysrc -f "${path_tmp_rc_conf}" initgfx_kmods="${kmod}"
 	sync
 	return 0
 }
@@ -174,7 +214,7 @@ setup_ati_amd()
 		kmod="/boot/modules/amdgpu.ko"
 	fi
 	kldload ${kmod}
-	sysrc initgfx_kmods="${kmod}"
+	sysrc -f "${path_tmp_rc_conf}" initgfx_kmods="${kmod}"
 	eval ${driver}_xorg_cfg > "${path_xorg_cfg}"
 	sync
 	return 0
@@ -206,22 +246,38 @@ setup_nvidia()
 	srcdir="${path_nvidia}/${driver}"
 
 	dir=/usr/local/etc/libmap.d 
-	tar -C ${srcdir}${dir} -cf - . | tar -C ${dir} -xkf -
+	tar -C ${srcdir}${dir} -cf - . | tar -C ${dir} -xf -
 
 	rc_conf_d_ldconfig ${srcdir}/usr/local/lib > \
 		/etc/rc.conf.d/ldconfig
 	ldconfig -m /usr/local/nvidia/${driver}/usr/local/lib
 
 	dir=/usr/local/lib/xorg/modules/drivers
-	tar -C "${srcdir}${dir}" -cf - . | tar -C "${dir}" -xkf -
-
+	# Restore symlink if it was removed or overwritten
+	if [ ! -L "${dir}/nvidia_drv.so" ]; then
+		if [ ! -d "/nvidia/${dir}" ]; then
+			mkdir -p "/nvidia/${dir}"
+		fi
+		rm -f "${dir}/nvidia_drv.so"
+		ln -s "/nvidia/${dir}/nvidia_drv.so" "${dir}/"
+	fi
+	tar -C "${srcdir}${dir}" -cf - . | tar -C "/nvidia/${dir}" -xf -
 	dir=/usr/local/lib/xorg/modules/extensions
-	tar -C "${srcdir}${dir}/.nvidia" -cf - . | tar -C ${dir} -xkf -
-	tar -C "${srcdir}${dir}" \
-		--exclude '.nvidia' -cf - . | tar -C "${dir}" -xkf -
 
-	dir=/usr/local/lib/vdpau
-	tar -C "${srcdir}${dir}" -cf - . | tar -C ${dir} -xkf -
+	# Restore symlink if it was removed or overwritten
+	for l in libglx.so libglx.so.1 libglxserver_nvidia.so \
+			 libglxserver_nvidia.so.1; do
+		if [ ! -L "${dir}/$l" ]; then
+			if [ ! -d "/nvidia/${dir}" ]; then
+				mkdir -p "/nvidia/${dir}"
+			fi
+			rm -f "${dir}/$l"
+			ln -s "/nvidia/${dir}/$l" "${dir}/"
+		fi
+	done
+	tar -C "${srcdir}${dir}/.nvidia" -cf - . | tar -C "/nvidia/${dir}" -xf -
+	tar -C "${srcdir}${dir}" \
+		--exclude '.nvidia' -cf - . | tar -C "/nvidia/${dir}" -xf -
 
 	if [ ${driver} -ge 390 ]; then
 		kmods="${srcdir}/boot/modules/nvidia.ko"
@@ -231,17 +287,46 @@ setup_nvidia()
 		kmods="${srcdir}/boot/modules/nvidia.ko"
 	fi
 	kldload ${kmods}
-	sysrc initgfx_kmods="${kmods}"
+	sysrc -f "${path_tmp_rc_conf}" initgfx_kmods="${kmods}"
 	nvidia_xorg_cfg > "${path_xorg_cfg}"
-	sync
 	return 0
+}
+
+is_vm()
+{
+	pciconf -lv | grep -B3 display | grep -E -q -i 'virtualbox|VMware'
+}
+
+get_fallback_driver()
+{
+	if sysctl machdep.bootmethod | grep -q BIOS; then
+		fallback_driver="vesa"
+	else
+		fallback_driver="scfb"
+	fi
+}
+
+write_fallback_cfg()
+{
+	(printf "Section \"Device\"\n"; \
+	 printf "\tIdentifier \"Card0\"\n"; \
+	 printf "\tDriver \"${fallback_driver}\"\n"; \
+	 printf "\tBusID \"PCI:$busID\"\n"; \
+	 printf "EndSection\n") > "${path_xorg_cfg}"
 }
 
 do_initgfx()
 {
-	local driver
-
 	unalias echo
+	if [ "$(kenv -q initgfx.detect.disable)" = "1" ]; then
+		del_stale_files
+		get_device_info
+		if ! is_vm; then
+			get_fallback_driver
+			write_fallback_cfg
+		fi
+		return
+	fi
 	if check_configured; then
 		initgfx_debug "Using previous configuration ..."
 		for m in ${initgfx_kmods}; do
@@ -252,42 +337,38 @@ do_initgfx()
 	fi
 	initgfx_debug "Creating new configuration ..."
 	del_stale_files
+	cp -a /etc/rc.conf "${path_tmp_rc_conf}"
 
-	# In VirtualBox we are done here
-	if (pciconf -lv | grep -B3 display | grep -q -i virtualbox); then
+	# In VirtualBox and VMware we are done here
+	if is_vm; then
 		save_config_id
 		return
 	fi
-	if sysctl machdep.bootmethod | grep -q BIOS; then
-		driver="vesa"
-	else
-		driver="scfb"
-	fi
+	get_fallback_driver
 	initgfx_debug "Auto-detecting graphics driver ..."
 	get_device_info
-	for i in nvidia intel ati_amd; do
+
+	# Prepare for a crash.
+	for i in nvidia ati_amd intel; do
 		if setup_${i}; then
 			initgfx_debug "Testing Xorg configuration ..."
 			if test_x; then
 				# FIXME: Without the delay the result is a
 				# reboot when using a Nvidia GPU.
-				sleep 3
+				__wait 3
 				save_config_id
+				cp -a "${path_tmp_rc_conf}" /etc/rc.conf
 				return
 			else
 				initgfx_warn "Failed to use $i driver. " \
-							 "Using ${driver} instead ..." >&2
+							 "Using ${fallback_driver} instead ..." >&2
 				del_stale_files
 			fi
 			break
 		fi
 	done
-	(printf "Section \"Device\"\n"; \
-	 printf "\tIdentifier \"Card0\"\n"; \
-	 printf "\tDriver \"${driver}\"\n"; \
-	 printf "\tBusID \"PCI:$busID\"\n"; \
-	 printf "EndSection\n") > "${path_xorg_cfg}"
-
+	write_fallback_cfg
+	cp -a "${path_tmp_rc_conf}" /etc/rc.conf
 	sysrc -x initgfx_kmods
 }
 
